### ISSUE TITLE
How to map url with args?

### ISSUE THREAD

**Issue by RicardoLopes91** [skornei/restserver#2]
Hello @skornei
I have a question for you, but before that, thank you for this project, you did such a great job.
My question is: Is it possible to map the URL of a controller with args?
Something like this example:

   
@RestController("/voodoo-vending-private/2.0/transaction")
    
    public class TransactionController {

        @GET
        @GetMapping("/{id}")
        @Produces(ContentType.APPLICATION_JSON)
        public TransactionEvent getTransactionEvent(Context context, RequestInfo request, ResponseInfo response){
        }

        @POST
        @PostMapping("/{id}/event")
        @Produces(ContentType.APPLICATION_JSON)
        @Accept(ContentType.APPLICATION_JSON)
        public Object Event(Context context, RequestInfo request, ResponseInfo response, TransactionEvent transactionEvent) {
       
        }
    }  
    
I have been searching for a solution, but I didn't found anything.
Thank you for your attention.

**Comment by skornei** [comment]
@RestController("/ping")
public class PingController {

Only over the controller
